### PR TITLE
Add Minecraft Education Support

### PR DESCRIPTION
**Pull request by Weather-OS**
This PR adds support for Minecraft Education and Minecraft Education Preview for the BetterRTX Installer.

### CODE REVIEW

**Comment by ABUCKY0** [comment]
Does Education Edition ***on Windows*** fully support RTX and BetterRTX?

**Comment by Weather-OS** [comment]
Yes, Yes it does. Same requirements as Regular Minecraft RTX.
Here's an screenshot from Minecraft Education Preview.
Minecraft Education also works.
Screenshot 2024-02-23 205033

**Comment by Weather-OS** [comment]
It's been 3 days. What is the status of this Pull request?

**Comment by ABUCKY0** [comment]
I forgot about it sorry. I'll look at it this afternoon

**Comment by ABUCKY0** [comment]
Update: My laptop decided to not work properly anymore so it'll be a few days before I can check if I have access to Minecraft Education Edition to test this PR.

**Comment by Weather-OS** [comment]
@ABUCKY0 Since this PR is basically dead, I've done the testing against this code and I can confirm that it does work on both the Preview build and the Production build of Minecraft Education.
You may decide to close the PR or merge it.

**Comment by ABUCKY0** [comment]
I’ve been dealing with school and other stuff I’ll check it tonight

**Pull request merged**
